### ISSUE TITLE
If a user is logged in, /admin will  give you dashboard.

### ISSUE THREAD

**Issue by visheshruparelia** [zense/alumni-dashboard#1]
It will check only when signing in whether that id is registered as an admin or not, and redirect to appropriate page, but if you are signed in and go to /admin it will give you the dashboard no matter whether you are admin or not. 
Check whether the user is admin or not when routing to /admin.
Use cancancan if required.

**Comment by vibhavagarwal5** [comment]
will do it and update it as required!

**Comment by visheshruparelia** [comment]
Solved using cancancan
