### ISSUE TITLE
Change view

### ISSUE THREAD

**Issue by visheshruparelia** [zense/alumni-dashboard#16]
-Add description field and event image in Event schema
-Also show user details while RSVPing for event

**Comment by visheshruparelia** [comment]
This is done, please check it @arkokoley 

PS- Image resolution needs to managed in events#show, events#index, it looks bad.(Functionality wise, everything is in place.

**Comment by arkokoley** [comment]
Image resolution isn't a blocking issue. Let's look it up later.
