### ISSUE TITLE
View Pending Mails from Sidekiq 

### ISSUE THREAD

**Issue by arkokoley** [zense/alumni-dashboard#17]
A page should be available on the admin dashboard which shows this list of mails which are pending delivery.

This can be done by getting the job queue and parsing it to show as a list.

**Comment by arkokoley** [comment]
As informed by @visheshruparelia, apparently there exists a sidekiq dashboard for rails. 

Please review that existing dashboard and respond on this chain.

**Comment by visheshruparelia** [comment]
Yes, added a link to the dashboard which will redirect to the sidekiq dashboard. The 'dead' section will have all the unsent mails.

**Comment by arkokoley** [comment]
Please make sure that the sidekiq dashboard is accessible only by the admin.

**Comment by visheshruparelia** [comment]
Done.
